class Usuario {
    - id: Long
    - nome: String
    - dataNascimento: Date
    - email: String
    - senha: String
}

class Administrador {
    - id: Long
    - matricula: Integer
}

class Cliente {
    - id: Long
    - cpf: String
}

class NivelAcesso {
    - codigo: Integer
    - descricao: String
}

class Endereco {
    - id: Long
    - logradouro: String
    - numero: String
    - complemento: String
    - bairro: String
    - cep: String
}

class Telefone {
    - id: Long
    - codArea: String
    - numero: String
}

class Cidade {
    - id: Long
    - nome: String
}

class Estado {
    - id: Long
    - nome: String
    - sigla: String
}

class Marca {
    - id: Long
    - nome: String
}

class ModeloCelular {
    - id: Long
    - nome: String
    - marca: Marca
}

class CaseProtetora {
    - id: Long
    - modelo: ModeloCelular
}

class Cor {
    - id: Long
    - nome: String
}

class Lote {
    - id: Long
    - fornecedor: Fornecedor
    - caseProtetora: CaseProtetora
}

class Fornecedor {
    - id: Long
    - nome: String
}

class Estoque {
    - id: Long
    - quantidade: Integer
}

class ItemVenda {
    - id: Long
    - caseProtetora: CaseProtetora
}

class Venda {
    - id: Long
    - pagamento: Pagamento
}

class Pagamento {
    - id: Long
    - data: Date
}

class Pix {
    - id: Long
    - chavePix: String
}

class CartaoDeCredito {
    - id: Long
    - numeroCartao: String
    - codigoSeguranca: String
    - bandeira: String
}

class BoletoBancario {
    - id: Long
    - banco: String
    - numeroBoleto: String
}

class ModoPagamento{
    id: Long
    data: Date
}

Administrador --|> Usuario
Administrador "*" o--> "1" NivelAcesso

Cliente --|> Usuario
Cliente "1" *--> "*" Endereco
Cliente "1" *--> "*" Telefone
Cliente "1" *--> "*" ModoPagamento

Endereco "*" o--> "1" Cidade
Cidade "*" o--> "1" Estado

ModeloCelular "*" o--> "1" Marca

CaseProtetora "*" o--> "1" ModeloCelular
CaseProtetora "*" o--> "*" Cor

Lote "1" o--> "1" Fornecedor
Lote "1" o--> "*" CaseProtetora

Estoque "1" o--> "*" Lote

ItemVenda "1" o--> "*" CaseProtetora
Venda "1" *--> "1" ItemVenda
Venda "1" *--> "1" Pagamento

Venda "1" o--> "1" Cliente

Pagamento "1" o--> "1" ModoPagamento
ModoPagamento "1" *--> "1" Pix
ModoPagamento "1" *--> "1" CartaoDeCredito
Pagamento "1" *--> "1" BoletoBancario